Version : 0.2

phases:
  install:
   runtime-versions:
     nodejs: 18
  commands:
    - echo "install dependncies"
    - npm install
build:
  commands:
  - echo "build app"
  - npm build
post_build:
  commands:
    - echo "Update file in s3 bucket"
    - aws s3 sync dist/Docker-react/my-app/  s3:/nitin-react  --delete
